### ISSUE TITLE
Binding this to F2?

### ISSUE THREAD

**Issue by kdato** [adoakley/efi-boot-to-fw-ui#1]
Hi,

through tinkering I lost the ability to enter my laptop's bios through pressing F2. I was wondering if there is a way to bind efi-boot-to-fw-ui's functionality to F2 using efibootmgr. If so, what is the epression I need to pass to efibootmgr?

There are a lot of efivars on my Laptop, I could try some of them, but I don't know the expression to pass to efibootmgr. Any advise?

Thanks.

**Comment by adoakley** [comment]
I don't think it's possible to bind to keys (without installing a bootloader of some kind).

My guess is that you've enabled fast boot mode in your laptop firmware settings (the "bios" screens).  If that's the case then you need to go into the firmware settings and turn fast boot off.  You may find efi-boot-to-fw-ui useful to get into the firmware settings.

**Comment by kdato** [comment]
Ok, thanks. I'll try.

**Comment by beedell-roke** [comment]
@kdato, did the suggestion remediate your problem?
