### ISSUE TITLE
On Void Linux - .../vars/ is .../efivars/

### ISSUE THREAD

**Issue by Kerrnel** [adoakley/efi-boot-to-fw-ui#3]
Although I changed that in main.c and rebuilt, still fails with 

```
 $ sudo ./efi-boot-to-fw-ui
open EFI variable failed: Not a directory

```
Will look further.

**Comment by adoakley** [comment]
It looks like the kernel interface changed.  That's quite an unusual thing to happen.  The old /sys/firmware/efi/vars interface was removed in https://github.com/torvalds/linux/commit/0f5b2c69a4cbe4166ca24b76d5ada98ed2867741 for Linux 6.0.

The old interface is documented [here](https://github.com/torvalds/linux/blob/master/Documentation/ABI/stable/sysfs-firmware-efi-vars) and the new one [here](https://github.com/torvalds/linux/blob/master/Documentation/filesystems/efivarfs.rst).

In the new interface you can write the attributes and the value to the file, there is no need to read the file first.  I think you might now be able to do this (but I've not tried it yet):
```
$ printf "\x7\x0\x0\x0\x1\x0\x0\x0\x0\x0\x0\x0" > /sys/firmware/efi/efivars/OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c
```

The data is:
* The attributes, 32 bits in little endian format.  The value is 0x00000007 - `EFI_VARIABLE_NON_VOLATILE | EFI_VARIABLE_BOOTSERVICE_ACCESS | EFI_VARIABLE_RUNTIME_ACCESS`.
* The value, 64 bits in little endian format.  The value is 0x0000000000000001 - `EFI_OS_INDICATIONS_BOOT_TO_FW_UI`.  

If the 1 line printf command works then there isn't much point in having this program.

**Comment by adoakley** [comment]
I verified that the command given above works.  This program is obsolete, so I've updated the README and will archive it.

Thanks for reporting the issue.
